DROP TABLE LEVEL2;

CREATE TABLE LEVEL2 
(
    id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY, 
    Animals 	BLOB,
    Flowers 	BLOB,
    Sports 		BLOB,
    Vehicles 	BLOB,
    PRIMARY KEY(id) 
);