DROP TABLE USERS;

CREATE TABLE USERS 
(
    id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY, 
    firstName   VARCHAR(255), 
    lastName    VARCHAR(255), 
    email       VARCHAR(255), 
    username    VARCHAR(255) NOT NULL,
    textPass    VARCHAR(255),
    imagePass   VARCHAR(255), V
    rgbPass     VARCHAR(255),
    Image 		BLOB,
    PRIMARY KEY(id) 
);


insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Test','One', 'test@test.com', 'test','Test@1234','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Ayana','Griffin', 'mireille63@gmail.com', 'GriffinAyana',')j$JNULK=7kx','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Edmundo','Vega', 'laurel56@kreiger.org', 'VegaEdmundo','Kr5m*^jc={Hg','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Yuk','Henry', 'pierce52@bernhard.info', 'HenryYuk','!+)2VnejK9f^','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Josphine','Davila', 'damaris.reichert@russel.com', 'DavilaJosphine',')WQ.wX@8-sCx','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Tony','Chaney', 'florian18@kunze.com', 'ChaneyTony','}4p@Uj+FW$V/','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Grady','Horn', 'gerardo.heidenreich@buckridge.com', 'HornGrady','DES6G.Jj>=NP','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Tabatha','Huynh', 'hills.jules@yahoo.com', 'HuynhTabatha','(4MWFq}+ezCE','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Tammy','Mcneil', 'qwelch@gmail.com', 'McneilTammy','Qe4B+_c}Y5qC','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Riley','Frazier', 'vada.dietrich@gmail.com', 'FrazierRiley','Xdcv63pARHC{','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Toshiko','Ibarra', 'sawayn.ebony@dickens.com', 'IbarraToshiko','G?%YzgKDV[!9','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Anissa','Lozano', 'omer.nienow@hintz.biz', 'LozanoAnissa','WJg)G!BNY5pj','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Perry','Lucero', 'huels.emery@gmail.com', 'LuceroPerry','nSx)Ahe2Y>Rs','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Rolland','Sharp', 'alabadie@gmail.com', 'SharpRolland','-fM8Z*CX!$GN','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Reanna','Wagner', 'vergie.denesik@lakin.com', 'WagnerReanna','H=$6uC(b?%_R','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Amberly','Robles', 'audra31@gmail.com', 'RoblesAmberly','gkG(4_DKb/>R','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Roberto','Lane', 'carmella70@hotmail.com', 'LaneRoberto','mJ-.[xcUK+Y8','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Neida','Lynch', 'maddison.moen@cruickshank.com', 'LynchNeida','^$b)6g8[NXm5','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Birdie','Glass', 'stanton.chanel@gmail.com', 'GlassBirdie','e=/a)3yMPg5q','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Hyacinth','Kramer', 'xwolff@hotmail.com', 'KramerHyacinth','pz!M^5AkC(t8','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Lorean','Hodges', 'lehner.joana@gmail.com', 'HodgesLorean','Q}Y=$$F2h_4c','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Barbie','Wiggins', 'veum.evie@leuschke.com', 'WigginsBarbie','*tqZQUkT8n+G','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Denese','Hicks', 'bertha55@schuster.biz', 'HicksDenese','LrgZ$v-A+7%S','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Bernie','Page', 'jnader@bednar.info', 'PageBernie','JS9(3z%=_T[$','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Mackenzie','Weiss', 'pearl.hane@casper.com', 'WeissMackenzie','Q32cNmWzwTr$','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Willia','Bray', 'jessika09@gmail.com', 'BrayWillia','p}v*76wVm2=F','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Juliette','Werner', 'deborah90@yahoo.com', 'WernerJuliette','zRe2B-N9+bF(','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Kendall','Baird', 'ogaylord@hirthe.com', 'BairdKendall','{pJL6a}t.d)V','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Dean','Macdonald', 'moses66@green.com', 'MacdonaldDean','^sn46@+VK?]5','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Harvey','Moore', 'hessel.morgan@mertz.com', 'MooreHarvey','!_85YZ-[ELvU','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Corazon','Hobbs', 'cormier.bessie@yahoo.com', 'HobbsCorazon','3Ayg7-^r?xbk','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Criselda','Black', 'josie46@gmail.com', 'BlackCriselda','NwtM85hc%x/B','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Magdalena','Lyons', 'lorenz33@hills.com', 'LyonsMagdalena','$qf8A(jywb2K','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Nikki','Foster', 'rhiannon12@brakus.com', 'FosterNikki','j)863ErQ.$BP','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Shirleen','Estrada', 'bradford.deckow@dare.org', 'EstradaShirleen','UH*!QuB$)C9@','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Vanesa','Hoover', 'anais62@hotmail.com', 'HooverVanesa','3v$tfKUWdX.2','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Ozie','Quinn', 'merritt.mayer@yundt.com', 'QuinnOzie','%Ak@d9hzJx{]','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Alexander','Drake', 'ryan.horacio@balistreri.biz', 'DrakeAlexander','84P*Kn!=by}q','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Danica','Baxter', 'schoen.adolphus@durgan.net', 'BaxterDanica','5xnVA]7M$=vw','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Harry','Greene', 'langosh.devyn@conn.com', 'GreeneHarry','%U*nb!4uc$W3','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Lamonica','Carroll', 'mariam.cruickshank@kuhic.com', 'CarrollLamonica','wTjq=b(6M.*9','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Warren','Stevens', 'ankunding.rose@yahoo.com', 'StevensWarren','8Cn*)]9}F=Hh','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Nancie','Wilcox', 'xlesch@hotmail.com', 'WilcoxNancie','r{U4yNs?$*VR','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Ewa','Carrillo', 'simeon.jacobs@sawayn.com', 'CarrilloEwa','M$p/z9nkjEdU','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Eugenia','Hale', 'harris.angelo@moen.com', 'HaleEugenia','!?ELa>v[%6ng','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Shon','Burgess', 'jamel.schamberger@hotmail.com', 'BurgessShon','P]R@>s9(Jx7d','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Gino','Howard', 'irunolfsdottir@hotmail.com', 'HowardGino',')9p>Cv5V/j$Y','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Cesar','Warner', 'clemmie64@gmail.com', 'WarnerCesar','!D_*^Vqz]5wP','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Hang','Huerta', 'lmacejkovic@abbott.com', 'HuertaHang','r(eAusT3E=8>','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Jonah','Hatfield', 'morton.champlin@gmail.com', 'HatfieldJonah','V/$r+DnxPqF8','image-pass','rgb-pass');
insert into users (firstName, lastName, email, username, textPass, imagePass, rgbPass) values ('Patricia','Webb', 'magali.satterfield@yahoo.com', 'WebbPatricia','E8WYt$Cz{wR)','image-pass','rgb-pass');


